### ISSUE TITLE
Soundemote TODO List 2017-12-28

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#149]
in order of priority

## Bugs
* [x] **PRIORITY**: Breakpoint modulator level/time/shape sliders are broken #150 
* [x] Standalone PrettyScope runs into crashes / nullptr, this is only happening in JUCE 5.
* [ ] GUI needs update on preset change: #113
* [x] AsyncCallInvoker memory leak #158 
* [x] Removing modulation connection causes crash #157
* [ ] Closing plugin causes crash #156
## Features
* [ ] upsampling filter for prettyscope
* [ ] Greg from OrangeTreeSamples needs that frequency locking tuner phase drift problem fixed
* [ ] modulation repainting / notification system
* [x] macro parameters
* [ ] get constrainer to work for FMD (due January 25) #154

**Comment by elanhickler** [comment]
hey robin where is the drawing code for the breakpoint stuff?

**Comment by RobinSchmidt** [comment]
OMG! this is ancient code that i never wanted to show anyone ...well, not yet at least. it's in class ModulatorCurveEditor

oh my god - that code needs clean up!

**Comment by elanhickler** [comment]
jim is working on it as we speak 👍

**Comment by RobinSchmidt** [comment]
ok, nice. i'll do a meta (or macro or whatever) mapper soon anyway (1-2 weeks). but if you have time pressure to have that feature immediately and jim is much faster, i'll have to back off a little. i'm looking forward to your release of torus generator, by the way. 

....do videos! that's what gets people interested. soundcloud doesn't really cut (imho), ...well at least, i like watching your youtube-videos, but the soundcloud demos give me nothing

**Comment by elanhickler** [comment]
i did release torus and there are videos... lol

?

**Comment by elanhickler** [comment]
but i guess i need usage videos

**Comment by RobinSchmidt** [comment]
well - yes, i've seen these 4-hour preset design and programming videos and watched half an hour of it. but they are really boring. you need videos that present the best patches - with prettyscope visualizations. these are goooood and interesting :-)

**Comment by RobinSchmidt** [comment]
but yes - this is good:
https://www.youtube.com/watch?v=igU0vjzBdbI
i did not see this yet. .. yes - i think, prettyscope videos with factory presets are very good promotion

**Comment by elanhickler** [comment]
those long videos are done live! I do live videos, live stuff will attract subscribers. My live videos will get better too.

**Comment by elanhickler** [comment]
Jim is having trouble getting the modulation curve editor to repaint based on a parameter changing. How do you make it repaint based on a parameter to change? We need to update the cursor position.

**Comment by RobinSchmidt** [comment]
you can register at any parameter as ParameterObserver. you need to inherit from ParameterObserver, call registerParameterObserver (somewhere in the constructor perhaps) and then override parameterChanged. and de-register in the destructor to avoid dangling pointers

**Comment by RobinSchmidt** [comment]
> Jim is having trouble getting the modulation curve editor to repaint based on a parameter changing

note that calling repaint from a parameter change call back may be dangerous. better to call repaintOnMessageThread() (it's a rather new function of DescribedComponent which is a baseclass of pretty much any gui object). the thing is that parameters may change from the audio-thread in case of automation and it is not allowed in juce to call repaint on any other thread than the message thread. i was hitting jassert when  trying to do so

**Comment by elanhickler** [comment]
but you're having to update the GUI when something changes like level/shape/time, so... I was going to look at how you did that.

**Comment by RobinSchmidt** [comment]
> Standalone PrettyScope runs into crashes / nullptr, this is only happening in JUCE 5.

well you are calling the constructor of OpenGLCanvas withh 3 nullptrs in OpenGLOscilloscope.cpp, line 17:

`Component * createMainContentComponent() { return new OpenGLCanvas(nullptr, nullptr, nullptr); }`

i added  few checks again nullptr (in 3 places) which fixes the crash - but apparently, with a nullptr, i won't work. you may want to look into why you pass a nullptr in the first place and change that

**Comment by RobinSchmidt** [comment]
> but you're having to update the GUI when something changes like level/shape/time, so... I was going to look at how you did that.

yes - that's the main purpose of the repaintOnMessageThread function. before discovering how to do that, i had some convoluted mechanism based on subclassing RWidget from juce::AsyncUpdater. that sucked. much better now, i think.

**Comment by RobinSchmidt** [comment]
> GUI needs update on preset change

i'm getting lots of compiler errors when trying to build MushroomGenerator of the type:

error C2065: 'midiFrequencyMasterPtr': undeclared identifier (compiling source file ..\..\..\Source\JerobeamMushroomPlugin

**Comment by elanhickler** [comment]
PrettyScopeEditor.cpp line 373 is where the 3 nullptrs get filled out.
![image](https://user-images.githubusercontent.com/9116575/34453309-7fbde9b2-ed0e-11e7-83bd-c755efa301ae.png)

Main.cpp like 69 creates a component with `createMainContentComponent()`
![image](https://user-images.githubusercontent.com/9116575/34453315-a642da52-ed0e-11e7-8e08-8a2444da1dd0.png)

line 17 OpenGLOscillscope.cpp:
![image](https://user-images.githubusercontent.com/9116575/34453316-baf949a4-ed0e-11e7-8fb1-c70f8550f34c.png)

no idea how to solve this, don't know how it all works...

maybe in MainWindow class / constructor I need to create some instances of PrettyScopeEditor/Module/AudioBuffer ?

**Comment by elanhickler** [comment]
line 15 of PrettyScopeEditor.cpp
![image](https://user-images.githubusercontent.com/9116575/34453336-7da66a86-ed0f-11e7-92f2-0eabf6d791f6.png)

this is where prettyScope ptr is assigned an object

**Comment by RobinSchmidt** [comment]
but wait - why actually isn't there a "createPluginFilter" function being called at startup - as is the case with other plugins?

**Comment by elanhickler** [comment]
hmmmmmm wait, you know i had to define JUCE_USE_CUSTOM_PLUGIN_STANDALONE_APP=1

but I didn't have to define that for my other plugins, maybe that's the issue.

**Comment by RobinSchmidt** [comment]
shouln't it be initialized as a "StandalonePlugin" (i love that term, btw.) like all other juce standalone "plugins"

**Comment by RobinSchmidt** [comment]
>  i had to define JUCE_USE_CUSTOM_PLUGIN_STANDALONE_APP=1

ah - ok - yes, maybe look into that then

**Comment by elanhickler** [comment]
wow wtf, it works. just commented out all code in Main.cpp

**Comment by RobinSchmidt** [comment]
haha! great1!

**Comment by elanhickler** [comment]
btw, check out my first FMD test: https://hearthis.at/soundemote/fmdtest1/

not using the macro controller yet, this is just from my experimentation.

seriously, have you ever heard a digital filter sound like that? this is just the tip of the iceberg.

**Comment by RobinSchmidt** [comment]
> btw, check out my first FMD test: https://hearthis.at/soundemote/fmdtest1/
> not using the macro controller yet, this is just from my experimentation.
very cool! ...working on the node-editor now (which will be used for the meta/macro/ whatever mapper)

> seriously, have you ever heard a digital filter sound like that? this is just the tip of the iceberg.
no - but i did not really look very much into that either and i'm also not very familiar with analog filters. however - sounds good indeed.

**Comment by elanhickler** [comment]
The principle of how FMD works is so simple. What happens when you modulate the PHASE of a sinewave of 0 hz with a sawtooth? What do you get out? A sawtooth! Because obviously you're just modulating a DC signal... actually that's as far as I understand. Then you need FM, filtering, multiple oscillators, yeah I don't get it haha.

**Comment by elanhickler** [comment]
basically the point is to send signal "through" oscillators, the oscillators can recreate the original signal but distorted in various ways or lock on to features (fundamentals / beats) of the input signal. You can get stuff that really sounds like distortion without clippers, but definitely a unique sound compared to clipping. 

like this: https://hearthis.at/soundemote/jerobeammushroom-analog-style-filtering/

**Comment by RobinSchmidt** [comment]
> send signal "through" oscillators

like using the input signal as phase ...or phase-offset?

**Comment by elanhickler** [comment]
use input signal as phase and frequency modulator, and if you have more components in the signal chain you could try sending some input signal or oscillator signal to modulate those. It's just a big fun frankenstein of modulation that creates endless variation.

**Comment by elanhickler** [comment]
crash :(

![image](https://user-images.githubusercontent.com/9116575/34471466-cffc82b2-ef07-11e7-9728-df699da1f9bd.png)


no idea why or how, will have to wait until it happens a bunch of times

**Comment by RobinSchmidt** [comment]
:-O very weird indeed. i have never encountered this. 0xFFFFFFFFFF....?

**Comment by RobinSchmidt** [comment]
damn! 3 new bugs? looks like a longer debugging session is due again. as for making the constrainer work: as said, i'm out of ideas with that and think we need to turn to the juce forum. should i do this for you or do you want to do that yourself?

**Comment by elanhickler** [comment]
you :)

**Comment by elanhickler** [comment]
yeah, i can't continue with all these bugs, because now I don't know if I'm doing something wrong.

**Comment by RobinSchmidt** [comment]
if all these problems are new since i introduced the meta-mapping system, look at sliders calling Parameter::setValue. this is illegal now for meta-controlled parameters (at least when they actually have a custom mapping - i'm not yet sure how to handle menus and buttons. i guess, a mapping function makes no sense there - yet they also work with meta-controlled parameters)

**Comment by elanhickler** [comment]
it might be from my code, already went back on your commits

**Comment by RobinSchmidt** [comment]
phew! at least not *all* my bad! ;-) ...or well, we'll see.  but watch out for this setValue/setNormalizedValue problem anyway. it's a change that i had to make that may break client code that calls Parameter::setValue

**Comment by RobinSchmidt** [comment]
maybe i should start to somehow document client-code-breaking changes....but actually the framework was meant for personal use ...hmmmm

**Comment by elanhickler** [comment]
no don't worry about that. I'm trying to let your framework be for personal use, I'm trying to move away from depending on your framework. With FMD I'm actually overriding all your paint methods. I will only be using your modulation system with FMD.

**Comment by elanhickler** [comment]
.....well, I need to not be overriding your stuff and I need to create my own classes from scratch, but I need your mod system and macro system for now.

**Comment by elanhickler** [comment]
im using your child module system... i can replace that by just instantiating parameters with myparams eventually.

**Comment by elanhickler** [comment]
i've isolated it to basic oscillator and midi mod source, but NOT basic envelope........ plot thicknes... wtf.

**Comment by elanhickler** [comment]
looks like it's just basic oscillator and not midi mod source

**Comment by elanhickler** [comment]
I isolated the crash completely!... well... this:

BasicOscillatorEditor.cpp
![image](https://user-images.githubusercontent.com/9116575/34687993-d3a0221e-f46d-11e7-83d8-5728ea412746.png)

**Comment by elanhickler** [comment]
fixed.

**Comment by elanhickler** [comment]
didn't mean to close

**Comment by elanhickler** [comment]
uhh nevermind, you should start documenting your changes that would break my code.

If I override certain functions, recreate those functions with your code with a copy and paste, and you change said code, my code no longer works, your code remains working, and I waste hours of time dealing with it.

We need a solution. 

I think you should help me somehow transition from using your framework.

**Comment by elanhickler** [comment]
I don't know what to do.

When I try to move away from your framework you do something that breaks my code

When I try to stick with your framework you don't have obvious features I need to make a decent gui.

**Comment by RobinSchmidt** [comment]
> provide paint methods for your sliders, for starters.

i have added a `setPainter` method to RSlider. you are supposed to pass a pointer to an object of a subclass of RSliderPainter. in your subclass, you will have to implement the `paint` function. in RSlider's `paint`, i check the pointer against nullptr, and if it's not a nullptr, i delegate the painting to the object - otherwise i paint directly. pretty simple infrastructure, but should be very flexible. you can do as many subclasses of RSliderPainter as you want and do whatever you want there. if it works, we can do the same for buttons and menus and also whole editors (if you need custom backgrounds, for example) and implement functions for the editors to set the painters for all embedded widgets

**Comment by RobinSchmidt** [comment]
> it seems you didn't fix the slider display name issue

what issue was that? there actually is no separate "display name". the slider's name is what is displayed. the underlying parameter, however, may (or may not) have a different name (and it's the parameter's name, which is used in the state-xml)

**Comment by elanhickler** [comment]
ok, you also need to have a setting of whether the slider should be vertical or horizontal... and type of drag scaling. Knobs need a totally different drag scaling, knobs drag scaling should not be based on size like sliders, and it needs to be vertical instead of horizontal.

**Comment by RobinSchmidt** [comment]
hmm...yes....i see. i wonder what's the best way to handle this. maybe a "type" member that can have values for horizontal, vertical and knob
